### ISSUE TITLE
Consider adding semantic version tags to the repository

### ISSUE THREAD

**Issue by creachadair** [minio/highwayhash#10]
This package has a `go.mod` file, but there are currently no release tags. For better integration with Go modules, would you be willing to start tagging versions? Even just running `git tag v0.0.1 master ; git push origin v0.0.1` would be sufficient to get the tag history started, without committing you to any API promises.

**Comment by harshavardhana** [comment]
Go modules will still work it will simply use the commit ID - semantic versioning is not needed IMO since this complies with Go's hash.Hash interface.

**Comment by creachadair** [comment]
> Go modules will still work it will simply use the commit ID - semantic versioning is not needed IMO since this complies with Go's hash.Hash interface.

You're right that a Go module will _work_ with a commit ID, but then you're left with the choice of either (a) manually pinning a commit ID, or (b) randomly building at HEAD whenever you update. 

(a) is what we currently do on kythe.io, and is the motivation for this PR: I'd like to pin to a labelled version so that we have some sense of a released version instead of a tip commit.

(b) is what modules is intended to get away from, though of course it has to support that case for people to migrate.

So I'd suggest this is still worth doing, even though it's not a hard requirement.

**Comment by creachadair** [comment]
Ping @harshavardhana, would you be willing to consider adding tag(s) in support of the above?

**Comment by creachadair** [comment]
Ping @harshavardhana, what do you think?

**Comment by creachadair** [comment]
Ping @harshavardhana, are you willing to make a call on this issue? Even if the answer is "no" it would be helpful to have the maintenance status of this package on record. Thanks!

**Comment by harshavardhana** [comment]
> Ping @harshavardhana, are you willing to make a call on this issue? Even if the answer is "no" it would be helpful to have the maintenance status of this package on record. Thanks!

@creachadair been busy we will do it

**Comment by harshavardhana** [comment]
Fixed by v1.0.0 tag

**Comment by creachadair** [comment]
Thank you!
