### ISSUE TITLE
[FYI] Linked Wikipedia page was deleted

### ISSUE THREAD

**Issue by michaelsanford** [minio/highwayhash#11]
Just an FYI.

The deletion log for https://en.wikipedia.org/wiki/HighwayHash reads:

```
07:12, 12 December 2018 Explicit (talk | contribs) deleted page HighwayHash
   (Expired PROD, concern was: No independent coverage. All sources mentioning
   HighwayHash are self-published by the creators of the hash function.)
```

WikiVisually still has a cached version [here](https://wikivisually.com/wiki/HighwayHash).

**Comment by harshavardhana** [comment]
Thanks // cc @aead

**Comment by michaelsanford** [comment]
Would you accept a PR with the article's contents as a markdown, maybe served as a github.io page for this repo?

**Comment by harshavardhana** [comment]
> Would you accept a PR with the article's contents as a markdown, maybe served as a github.io page for this repo?

Yes @michaelsanford - that is fine too. We may even point to official Google project instead for documentation.

**Comment by michaelsanford** [comment]
@harshavardhana Ok! In that case I'll make a little _gh-pages_ site to replace the missing wikipedia page.

If you don't have a preference, I'll implement it as a folder ([rather than a branch](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)).

**Comment by aead** [comment]
I've created an issue at the google repo, too. The argument for deleting may be correct (formally ?!) but does not reflect the actual situation. HighwayHash is used by multple projects and it would pretty easy to add them into the page references...

**Comment by michaelsanford** [comment]
Ok! In that case I'll hold off for now and hope the Wikipedia page returns.

**Comment by jan-wassenberg** [comment]
Thanks, Andreas, for opening the issue on the HWH repo.

Would be nice if the article were published again. Can you help create a new one? That would work better than if we did it. From the Minio issue, glad to see there's still a cached version:
https://wikivisually.com/wiki/HighwayHash

Besides Minio, other users include Tensorflow and https://github.com/google/riegeli (compressed string records).

FYI I'll have sporadic network access in the next 2 weeks.

**Comment by michaelkaye** [comment]
Hi there; just hoping to wake this issue up - came across HighwayHash and both the wikipedia link and the cached version have now become unavailable.

**Comment by harshavardhana** [comment]
I would suggest someone to republish it @michaelkaye @michaelsanford on Wikipedia
