### ISSUE TITLE
Question: Whats the meaning of key parameter?

### ISSUE THREAD

**Issue by a-urth** [minio/highwayhash#12]
Its not exactly clear from the docs nor from examples, how to use key parameter for hash computation except that it should be exactly 32bytes long.
What role it plays and how it should be used?

**Comment by harshavardhana** [comment]
@a-urth you should read about highwayhash specification published by Google https://github.com/google/highwayhash

**Comment by aead** [comment]
@a-urth You are asking basically this: https://crypto.stackexchange.com/questions/15935/is-there-a-difference-between-prf-and-a-hash-function - For further explanation you will need to look into introductions to (symmetric) cryptography.

**Comment by a-urth** [comment]
Thank You very much @aead that helped a lot!
