### ISSUE TITLE
[question] highwayhash can be used to as hmac?

### ISSUE THREAD

**Issue by detailyang** [minio/highwayhash#13]
Hello.

I just want to know highwayhash can be used to as hmac hash function ?

**Comment by detailyang** [comment]
I think it's okay:)

**Comment by aead** [comment]
@detailyang No, HighwayHash is a VIL-PRF while HMAC is a generic construction to transform a FIL-PRF that is secure under related-key attacks into prefix-free VIL-PRF. Therefore, you cannot simply use HighwayHash as inner FIL-PRF for HMAC without careful analysis.

**Comment by detailyang** [comment]
@aead many thanks， gotcha:)
