### ISSUE TITLE
highwayhashAVX2_amd64.s: no such instruction: data ·consAVX2 , while building NATS, using gollvm

### ISSUE THREAD

**Issue by advancedwebdeveloper** [minio/highwayhash#15]
I was trying to build [NATS.io's Go client lib](https://github.com/nats-io/nats.go) using [gollvm](https://go.googlesource.com/gollvm/) .
I am not familiar with the implementation of your algorithm and required SIMD - but it would be good if you could consider some adoption for LLVM.

So [this](https://github.com/nats-io/nats.go/issues/592) is an actual bug report, for covering this from the side of NATS.io's committers.

CC @harshavardhana @fwessels @aead 
BCC @thanm @cherrymui 

Ivan

**Comment by aead** [comment]
@advancedwebdeveloper We cannot easily add support for gollvm since it differs in subtle ways from the standard Go compiler.
For example:
> Gollvm is currently supported only for x86_64 and aarch64 Linux.

> The main Go runtime supports generation of accurate stack maps, which allows the garbage collector to do precise stack scanning; gollvm does not yet support stack map generation (note that we're actively working on fixing this), hence for gollvm the garbage collector has to scan stacks conservatively (which can lead to longer scan times and increased memory usage). The main Go runtime compiles to a different calling convention, whereas Gollvm uses the standard C/C++ calling convention. There are many other smaller differences as well.

Also, gollvm is not meant to be a drop-in replacement for the standard Go compiler:
> Gollvm is not intended as a replacement for the main Go compiler -- the expectation is that the bulk of users will want to continue to use the main Go compiler due to its superior compilation speed, ease of use, broader functionality, and higher-performance runtime. Gollvm is intended to provide a Go compiler with a more powerful back end, enabling such benefits as better inlining, vectorization, register allocation, etc.

See: https://go.googlesource.com/gollvm/#workarea

Is there any specific reason to use gollvm?

**Comment by harshavardhana** [comment]
FWIW anything beyond standard Go compiler we don't need to add support @aead

**Comment by cherrymui** [comment]
Does it work with gccgo? Gollvm uses "gccgo" build tag (as it is pretty similar to gccgo). It seems the file already has "!gccgo" tag. Not sure why it doesn't work.

**Comment by advancedwebdeveloper** [comment]
@cherrymui , could check it?
I wonder how HighwayHash's could be compiled into LLVM's IR. Perhaps any version in C could allow to review and get some ideas?
Does it make sense to use experience of an old [dragonegg](http://dragonegg.llvm.org/) project ?

**Comment by aead** [comment]
I've sent a PR to add support for the `noasm` tag such that it will be possible to opt-out of any platform-specific implementation: #16

**Comment by aead** [comment]
PR #16 is merged. @advancedwebdeveloper Please use the latest version (`v1.0.1`) in your build and specify the `--tags noasm` tag.

**Comment by aead** [comment]
Closing this as #16 **should** address the linked build issues. Please, re-open otherwise.
