### ISSUE TITLE
runtime.support_avx2 not defined

### ISSUE THREAD

**Issue by mdcnz** [minio/highwayhash#6]
Hello, 

It appears `go test` fails in highwayhash with a development version of go:

```
github.com/minio/highwayhash.supportsAVX2: relocation target runtime.support_avx2 not defined
github.com/minio/highwayhash.supportsAVX2: undefined: "runtime.support_avx2"
```
This is likely due to the recent removal of runtime.support_avx2. It was replaced with a cpu package runtime/internal/cpu.X86.HasAVX2.

This is with:
highwayhash version commit 9c7e959
go version devel +a3c75d9 Tue Apr 24 01:06:17 2018 +0000 linux/amd64

See this [issue](https://github.com/golang/go/issues/15403).
Possibly relevant [change](https://go-review.googlesource.com/c/go/+/102737) and [another change](https://github.com/golang/go/commit/d0712096b32d032b0b83a5eb899a7359a830732b).

Regards, Mark

**Comment by harshavardhana** [comment]
We don't support devel yet @mdcnz - but thanks for opening the bug we will keep track. Let us know if you see any issues with go latest releases.

**Comment by aead** [comment]
@mdcnz I'm aware of this problem. I've proposed and still work on a general cpu package at `x/sy/cpu`.
See: golang/go/#24843

**Comment by mdcnz** [comment]
Thanks @aead, in my case that fixes the issue.
